---
- name: Add FB users
  hosts: all
  become: yes
  tasks: 
  - name: add new users
    ansible.builtin.user:
      name: Drewber
      groups: sudo,admin
      append: yes
  - name: add new users
    ansible.builtin.user:
      name: Nik
      groups: sudo,admin
      append: yes
  - name: add new users
    ansible.builtin.user:
      name: Alessandro
      groups: sudo,admin
      append: yes
  - name: add new users
    ansible.builtin.user:
      name: Jerry
      groups: sudo,admin
      append: yes
  - name: add new users
    ansible.builtin.user:
      name: testuser2
      groups: sudo,admin
      append: yes
      update_password: on_create
      password: '123456'