---
- name: Add FB users
  hosts: all
  tasks: 
  - name: add new users
    ansible.builtin.user:
    - name: Drewber
      groups: sudo,admin
      append: yes
    # #- name: Nik
    #   groups: sudo,admin
    #   append: yes
    # - name: Alessandro
    #   groups: sudo,admin
    #   append: yes
    # - name: Jerry
    #   groups: sudo,admin
    #   append: yes
    # - name: testuser1
    #   groups: admin
    #   append: yes
    #   password: 123456