- name: Install OpenVPN
  hosts: ansible-lab-controller
  gather_facts: true
  vars:
    ansible_become: true
    openvpn_server_hostname: 40.118.166.56
  roles:
  - role: ansible-role-openvpn
    clients: client1