---

# - name: run command update and upgrade
#   ansible.netcommon.cli_command:
#     command: 
- name: Update and upgrade hosts
  hosts: 
      ansible-lab-controller:
      ansible_host: 10.1.1.4
  children:
    ansible_lab_hosts:
      hosts:
        ansible-lab-host1:
          ansible_host: 10.1.2.4
        ansible-lab-host2:
          ansible_host: 10.1.2.5
        ansible-lab-host3:
          ansible_host: 10.1.2.6
  become: true
  become_user: root
  tasks:

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid=3600

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: Check if a reboot is needed for Debian and Ubuntu boxes
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no

  - name: Reboot the Ubuntu Server
    reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    coonnect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists